// Localhost Test

### Get all contacts
GET http://localhost:8080/users

### Get by ID
GET http://localhost:8080/users/
###
GET http://localhost:8080/users/
###
GET http://localhost:8080/users/
###
GET http://localhost:8080/users/

### Create new contact
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "nickyang00",
    "email": "yangnick@gmail.com",
    "password": "password123", 
    "profile": {
      "firstName": "Nick",
      "lastName": "Yang",
      "age": "23",
      "gender": "Male",
      "height": "65", 
      "weight": "185", 
      "goals": "Lose weight and gain strength." 
    }
}

### Update contact
PUT http://localhost:8080/users/65b315d155960690ee55e7b0
Content-Type: application/json

{
      "username": "nickyang00",
      "email": "yangnick@gmail.com",
      "password": "password456", 
      "profile": {
        "firstName": "Nick",
        "lastName": "Yang",
        "age": "23",
        "gender": "Male",
        "height": "65", 
        "weight": "185", 
        "goals": "Gain weight and jump higher." 
      }
}

### Delete contact
DELETE http://localhost:8080/users/65b329573427cc822e5de37a
Content-Type: application/json

// Production Test 

### Get all contacts
GET https://fitness-tracker-q4c5.onrender.com/users/

### Get by ID
GET https://fitness-tracker-q4c5.onrender.com/users/65d00489254a561bbe2db5a5
###
GET https://fitness-tracker-q4c5.onrender.com/users/65d01a9d9181e77b3ef5ad37
###
GET https://fitness-tracker-q4c5.onrender.com/users/65d01b169181e77b3ef5ad38

### Create new contact
POST https://fitness-tracker-q4c5.onrender.com/users/
Content-Type: application/json

{
    "username": "nickyang00",
      "email": "yangnick@gmail.com",
      "password": "password123", 
      "profile": {
        "firstName": "Nick",
        "lastName": "Yang",
        "age": "23",
        "gender": "Male",
        "height": "65", 
        "weight": "185", 
        "goals": "Lose weight and gain strength." 
      }
}

### Update contact
PUT https://fitness-tracker-q4c5.onrender.com/users/65d04bc57d7c4d86bc2427fa
Content-Type: application/json

{
    "username": "nickyang00",
      "email": "yangnick@gmail.com",
      "password": "password456", 
      "profile": {
        "firstName": "Nick",
        "lastName": "Yang",
        "age": "23",
        "gender": "Male",
        "height": "65", 
        "weight": "185", 
        "goals": "Gain weight and jump higher." 
      }
}

### Delete contact
DELETE https://fitness-tracker-q4c5.onrender.com/users/65d04bc57d7c4d86bc2427fa
Content-Type: application/json
